name: my3friends
favicon: null
layout_spectrum: 1
typography_spectrum: 0.91142
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#080808'
    - '#57b521'
    - '#5d5d5d'
    - '#fbc5e6'
    - '#ca0077'
  brandStrength: 0.45511288894340396
  lightness: 0.8809758520219475
  saturation: 0.9455525281373411
  rhythmicContrast: 0.3534793187864125
purpose: []
